name: 'Get $ Catched Dependencies'
description: 'Get the dependencies that were cached in the previous step'
runs:
  using: 'composite'
  steps:
    - name: Get cached dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash